[package]
name = "shake256"
version = "0.1.0"
edition = "2021"

[dependencies]
plonky2 = { workspace = true }
anyhow = { workspace = true }
sha3 = { workspace = true }
bit-operations = { path = "../bit-operations" }
keccak-permutation = { path = "../keccak-permutation" }

[dev-dependencies]
hex = { workspace = true }